name: Epic
description: An item to track new feature for this project.
type: "Epic"
projects: ["Fortress-Wars/2"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the epic.
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes:
      description: The list of target dates for the epic.
      # value: |
      #   | Target                | Start      | End        |
      #   | --------------------- | ---------- | ---------- |
      #   | Development & Testing | 00/00/0000 | 00/00/0000 |
      #   | System Testing        | 00/00/0000 | 00/00/0000 |
      #   | Beta Testing          | 00/00/0000 | 00/00/0000 |
      #   | Pre-Release           | 00/00/0000 | 00/00/0000 |
      #   | Release               | 00/00/0000 | 00/00/0000 |
    validations:
      required: true
  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: (No need to check these boxes)
      options:
        - label: Development & Testing Done
        - label: System Testing Done
        - label: Beta Testing Done
        - label: Pre-Release Done
        - label: Release Done
        - label: All features are done
        - label: All code is merged to main
        - label: Documentation for the epic is created.