name: Epic
description: An item to track new feature for this project.
type: "Epic"
projects: ["Fortress-Wars/2"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the epic.
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes: timeline
    description: The list of target dates for the epic.
    validations:
      required: true
    value: |
      | Target                | Start      | End        |
      | --------------------- | ---------- | ---------- |
      | Development & Testing | __/__/____ | __/__/____ |
      | System Testing        | __/__/____ | __/__/____ |
      | Beta Testing          | __/__/____ | __/__/____ |
      | Pre-Release           | __/__/____ | __/__/____ |
      | Release               | __/__/____ | __/__/____ |
  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: (No need to check these boxes)
      options:
        - label: Development & Testing Done
        - label: System Testing Done
        - label: Beta Testing Done
        - label: Pre-Release Done
        - label: Release Done
        - label: All features are done
        - label: All code is merged to main
        - label: Documentation for the epic is created.